import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='bg-white p-5'>
          <Link className='mr-3 font-extrabold' href={'/'}>
            Greenforum
          </Link>
          <Link className='mr-3' href={'/list'}>
            List
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
